# Generated by Django 5.0.6 on 2024-06-18 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(default='null', upload_to='Client', verbose_name='Imagen')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Creado el ')),
                ('update_ad', models.DateTimeField(auto_now=True, verbose_name='Actualizado el ')),
            ],
        ),
        migrations.CreateModel(
            name='ImageClie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(default='null', upload_to='ImageClie', verbose_name='Imagen')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_ad', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Categoria')),
            ],
        ),
    ]
